apiVersion: v1
kind: Pod
metadata:
  name: hostpath-violation
  namespace: audit-zone
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: host-volume
      mountPath: /mnt/host
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
