apiVersion: v1
kind: Pod
metadata:
  name: root-user-violation
  namespace: audit-zone
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0
