apiVersion: v1
kind: Pod
metadata:
  name: hostpath-fixed
  namespace: audit-zone
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: temp-volume
      mountPath: /mnt/data
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
  volumes:
  - name: temp-volume
    emptyDir: {}
