apiVersion: v1
kind: Pod
metadata:
  name: root-user-fixed
  namespace: audit-zone
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
